project:
  type: website

website:
  title: "Bezawit Lake "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Events
      - href: blog.qmd
        text: Blog
  sidebar:
    style: "docked"
    logo: "./images/user.png"
    search: true
    collapse-level: 2
    include: sidebar_info.html
    contents:
      - icon: github
        text: Github
        url: https://github.com/bezawitlake
      - icon: envelope
        text: "Email"
        url: mailto:dz24190@bristol.ac.uk
      - icon: linkedin
        text: LinkedIn
        url: https://www.linkedin.com/in/bezawit-lake/
      - icon: medium
        text: "Medium Blog"
        url: https://medium.com/@bezawitl
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



