project:
  type: website

website:
  title: "A.N. Other's academic homepage (edit in _quarto.yml)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Events
      - href: blog.qmd
        text: Blog
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/IntelligentSystemsLaboratory
      - icon: envelope
        text: "Email"
        url: mailto:dz24190@bristol.ac.uk
      - text: "Medium Blog"
        url: https://medium.com/@bezawitl
      - text: Pro-AI CDT
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



